algoritmo "Praticando"
// Função : Treino de funções nativas
// Autor : Paulo Alvares
// Data : 04/01/2023
// Seção de Declarações 
var
   x1, x2 : real
   y, z2 : inteiro
   z1 : caractere
inicio
   x1 <- raizq(9) + raizq(100)
   escreval(x1)
   x2 <- 12 * pi
   escreval(x2)
   y <- randi(20)
   escreval(y)
   z1 <- maiusc("brasil")
   escreval(z1)
   z2 <- compr("casa")
   escreval(z2)
fimalgoritmo
