# -*- coding: utf-8 -*-
"""Imersão Python - Aulas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Weuj0aJ6BUlhWPXNxImUwtztqPYtntf2

**Aula 2 - Importação**
"""

import pandas as pd

df_principal = pd.read_excel("/content/planilha_imersao_python.xlsx", sheet_name="Principal")
df_principal

# df_principal.head(10) - Primeiras 10 tuplas

df_total_acoes = pd.read_excel("/content/planilha_imersao_python.xlsx", sheet_name="Total_de_acoes")
df_total_acoes

df_ticker = pd.read_excel("/content/planilha_imersao_python.xlsx", sheet_name="Ticker")
df_ticker

df_chatgpt = pd.read_excel("/content/planilha_imersao_python.xlsx", sheet_name="Chatgpt")
df_chatgpt