numero = str(input('Digite um número entre 0 e 9999: '))
print('Unidade: {}'.format(numero[3]))
print('Deneza: {}'.format(numero[2]))
print('Centena: {}'.format(numero[1]))
print('Milhar: {}'.format(numero[0]))
