Algoritmo "operadores_logicos"
  Var
    value01, value02, value03: inteiro
  Inicio
    value01 <- 2
    value02 <- 3
    value03 <- 5
    
    escreval("true e false são iguais?", verdadeiro e falso)
    escreval("value01 é igual a value02 ou value03 é maior que value01?", (value01 = value02) ou (value03 > value01))
    escreval("qual é o valor negado de 'value01 é igual a value02 ou value03 é maior que value01'?", nao((value01 = value02) ou (value03 > value01)))
Fimalgoritmo