a = (2, 5, 4)
b = (5, 8, 1, 2)
c = b + a
print(c)
print(len(c))
print(c.count(5))
print(c.count(4))
print(c.count(9))
print(c.index(8))
print(c.index(4))
print(c.index(2))
print(c.index(2, 4))
print(c.index(5, 1))
