Algoritmo "teste-escopo"
Var
   number1, number2: inteiro
Procedimento routine(value1, value2: inteiro)
Var
   digit1, digit2: inteiro
Inicio
   digit1 <- value1
   digit2 <- value2
   escreva(number1, number2, value1, value2, digit1, digit2)
FimProcedimento
Inicio
   number1 <- 5
   number2 <- 3
   routine(number1, number2)
   escreva(number1, number2, value1, value2, digit1, digit2)
Fimalgoritmo